# syntax=docker/dockerfile:1.4

FROM python:3.8-alpine3.16

RUN <<-EOF
  apk add --no-cache make=4.3-r0
  adduser -D microblog
EOF

WORKDIR /home/microblog
# COPY . .
COPY migrations migrations
COPY requirements requirements
COPY microblog.py test.sh Makefile .pylintrc pytest.ini ./

RUN <<-EOF
  python -m venv .venv
  .venv/bin/pip3 install -r requirements/test.txt
EOF

ENV FLASK_APP microblog.py

RUN <<-EOF
  chmod +x test.sh
  chown -R microblog:microblog ./
EOF

USER microblog

EXPOSE 5000
ENTRYPOINT ["./test.sh"]