"""increate password hash length

Revision ID: 039616bdb613
Revises: ac1d6115ccbb
Create Date: 2025-12-04 17:19:24.736268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039616bdb613'
down_revision = 'ac1d6115ccbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
